import { Geist, Geist_Mono } from "next/font/google";
// src/app/layout.jsx
import "@/styles/globals.css"; // ← global base

// src/app/dashboard/layout.jsx
import "@/styles/dashboard.css"; // ← sidebar, layout del panel

// src/app/dashboard/usuarios/page.jsx
import "@/styles/usuarios.css"; // ← estilos propios de esta vista

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
